### PR TITLE
Better (faster) backend, and get it actually working

### PR DESCRIPTION
**Pull request by RedstoneWizard08**

### CODE REVIEW

**Comment by RedstoneWizard08** [comment]
@ravinder-Olivier pinging you for this xD

**Comment by ravinder-Olivier** [comment]
Oh my goodness. Wow. That's amazing. Thanks so much mate!

**Comment by RedstoneWizard08** [comment]
BRO IM NOT DONE

**Comment by RedstoneWizard08** [comment]
@ravinder-Olivier please wait for it to not be a draft next time

**Comment by ravinder-Olivier** [comment]
Oh, I'm sorry, I was using different mobile client and it just showed pr and merge option. My bad


Sent via the Samsung Galaxy S21 Ultra 5G, an Unlocked 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
